"""make_designation_nullable

Revision ID: 825aa43abf9f
Revises: f45429687eeb
Create Date: 2026-04-22 17:10:04.075648

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '825aa43abf9f'
down_revision: Union[str, Sequence[str], None] = 'f45429687eeb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('users', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.drop_constraint(op.f('users_organization_id_fkey'), 'users', type_='foreignkey')
    op.drop_column('users', 'organization_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('organization_id', sa.UUID(), autoincrement=False, nullable=True))
    op.create_foreign_key(op.f('users_organization_id_fkey'), 'users', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.alter_column('users', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
