"""update models

Revision ID: f45429687eeb
Revises: 1ccd5079590b
Create Date: 2026-04-22 12:22:18.097112

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f45429687eeb'
down_revision: Union[str, Sequence[str], None] = '1ccd5079590b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employee_statutory_id'), table_name='employee_statutory')
    op.drop_index(op.f('ix_memberships_id'), table_name='memberships')
    op.drop_index(op.f('ix_organizations_id'), table_name='organizations')
    op.drop_index(op.f('ix_organizations_slug'), table_name='organizations')
    op.create_unique_constraint(None, 'organizations', ['name'])
    op.drop_column('organizations', 'slug')
    op.alter_column('users', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=False)
    op.drop_index(op.f('ix_users_id'), table_name='users')
    op.drop_column('users', 'reset_token')
    op.drop_column('users', 'verification_token')
    op.drop_column('users', 'role')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('role', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('verification_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.add_column('users', sa.Column('reset_token', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.create_index(op.f('ix_users_id'), 'users', ['id'], unique=False)
    op.alter_column('users', 'designation',
               existing_type=sa.VARCHAR(),
               nullable=True)
    op.add_column('organizations', sa.Column('slug', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'organizations', type_='unique')
    op.create_index(op.f('ix_organizations_slug'), 'organizations', ['slug'], unique=True)
    op.create_index(op.f('ix_organizations_id'), 'organizations', ['id'], unique=False)
    op.create_index(op.f('ix_memberships_id'), 'memberships', ['id'], unique=False)
    op.create_index(op.f('ix_employee_statutory_id'), 'employee_statutory', ['id'], unique=False)
    # ### end Alembic commands ###
